### ISSUE TITLE
standardize on recommended docker pid=1 entrypoint

### ISSUE THREAD

**Issue by alonswartz** [tklx/tracker#4]
Some options in no specific order:
- tini
- s6-overlay
- dumb-init
- baseimage-docker
- gosu
- phusion runinit
- daemontools setuidgid (doesn't handle signals?)

**Comment by a3s7p** [comment]
[tini](https://github.com/krallin/tini/blob/master/src/tini.c) is really small and does everything that's required of it as PID 1. Fairly good barebones option.

> Tini is a very small file (in the 10KB range), so it doesn't add much weight to your container. The statically-linked version is bigger, but still < 1M.

[s6-overlay](https://github.com/just-containers/s6-overlay) seems to provide something very similar to runit, but properly optimized for Docker usage. Also a good option which is a bit larger than tini but includes all sorts of helper utilities (logging, setuidgid etc).

> And what about numbers? s6-overlay takes more or less 904K compressed and 3.4M uncompressed, that's very cheap! 

[dumb-init](https://github.com/Yelp/dumb-init/blob/master/dumb-init.c) and tini are more or less the same i. e. just a signal proxy which reaps.

> Statically compiled dumb-init is over 700KB due to glibc, but musl is now an option. When statically compiled with musl the binary size is around 20KB.

[baseimage-docker](https://github.com/phusion/baseimage-docker) is not an option because it's too heavy, so is my_init (which is its PID1) by itself since it is a Python script — TKLX base does not include a Python interpreter by default and probably shouldn't.

runit was not meant for Docker and doesn't know to handle e. g. TERM properly.

setuidgid is not a proper PID 1 substitute since as you mentioned, it doesn't handle signals.

gosu is like a setuidgid but the thing about it is that after launching the child it eliminates itself from the equation altogether which leaves the child to handle the signals on its own as I understand it. Which means that we depend on the launched process to reap its children/grandchildren properly.

So that leaves us with the choice of s6, tini or dumb-init. Depending on what we require of the init system, could pick s6 as a Swiss Army Knife type of option, or either one of the latter (which are both very light). Which one in particular depends on which options we value more — tini supports subreaper mode (reaping processes reparented to it when not running as PID 1) and has better logging, dumb-init can rewrite signals (e. g. receive TERM, send QUIT to child instead) and [handle job control properly](https://github.com/Yelp/dumb-init/blob/master/dumb-init.c#L69). Both can send signals to either only direct children or the process group.

**Comment by alonswartz** [comment]
Great review. Thoughts on [gosu](https://github.com/tianon/gosu)?

**Comment by a3s7p** [comment]
@alonswartz, I edited the comment (you must have caught the version with the gosu paragraph still missing). Basically it's not a PID 1 candidate IMO, but it can be used in lieu of setuidgid. s6-overlay includes its own setuidgid so I'm thinking it might be best to just go with that.

**Comment by alonswartz** [comment]
For now we'll go with tini, does the job. For example https://github.com/tklx/mongodb/commit/3d0d64ff4ee68d4ca52287597801f92cd0f8fa8b
